# docker-compose.yml
services:
  db-migrate:
    build: .
    image: omni-backend
    env_file:
      - .env.docker
    # Overrides the default start command to just run migrations
    command: bun run db:migrate
    depends_on:
      postgres:
        condition: service_healthy
  backend:
    build: .
    image: omni-backend
    env_file:
      - .env.docker
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: omni
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: omni
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omni"]
      interval: 1s
      timeout: 1s
      retries: 30

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 1s
      timeout: 1s
      retries: 30

volumes:
  pgdata:
